# baseURL
@baseURL = http://localhost:3000/api/v1

###
# Get License File
POST {{ baseURL }}/licenses
Content-Type: application/json

{
    "machineId": "OMCKS-QKFTN-IVRMY-LYPTJ",
	"expires": 1771186124,
    "validFrom": 1671186124,
    "isTrial": false,
    "maxUsers": 10,
    "maxCameras": 10,
    "assignmentSupport": true,
    "communicationsSupport": true
}
